# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170714_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='uploads/profile/default.jpg', upload_to='uploads/profile/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_stage',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
