# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='fake_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
