# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170716_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_to_category),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_offer',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
