# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170716_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount_offer',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
